import React, { useState, useRef, useEffect, KeyboardEvent } from 'react';
import { useStore } from '../store/useStore';
import { fileCommands, modelCommands } from '../lib/tauri';

interface ChatInputProps {
  conversationId: string;
}

export default function ChatInput({ conversationId }: ChatInputProps) {
  const [message, setMessage] = useState('');
  const [attachedFiles, setAttachedFiles] = useState<string[]>([]);
  const [isComposing, setIsComposing] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  
  const {
    addMessage,
    updateMessage,
    isGenerating,
    setIsGenerating,
    selectedModelId,
    modelLoaded,
    inferenceSettings,
    projectPath,
  } = useStore();

  // Auto-resize textarea
  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 200)}px`;
    }
  }, [message]);

  // Handle send message
  const handleSend = async () => {
    if (!message.trim() || isGenerating || isComposing) return;

    // Check model loaded
    if (!modelLoaded || !selectedModelId) {
      // Show alert or toast about loading model first
      return;
    }

    // Add user message
    addMessage(conversationId, {
      role: 'user',
      content: message.trim(),
      files: attachedFiles.map(f => ({ 
        name: f.split('/').pop() || f, 
        path: f, 
        size: 0 
      })),
    });

    const userMessage = message.trim();
    setMessage('');
    setAttachedFiles([]);

    // Start generating response
    setIsGenerating(true);
    
    // Create assistant message placeholder
    addMessage(conversationId, {
      role: 'assistant',
      content: '',
    });
    
    // Get the created message ID (it's the last one)
    const state = useStore.getState();
    const conv = state.conversations.find(c => c.id === conversationId);
    const assistantMessageId = conv!.messages[conv!.messages.length - 1].id;

    try {
      await generateResponse(conversationId, assistantMessageId, userMessage);
    } catch (error) {
      console.error('Generation error:', error);
      updateMessage(conversationId, assistantMessageId, 
        `❌ **Error**: Failed to generate response.\n\n${error instanceof Error ? error.message : 'Unknown error'}\n\nPlease check that the model is properly loaded.`
      );
    } finally {
      setIsGenerating(false);
    }
  };

  // Simulate generation (will be replaced with actual Tauri call)
  const generateResponse = async (
    conversationId: string,
    messageId: string,
    prompt: string
  ) => {
    const responses = [
      `I understand you're asking about: **${prompt.slice(0, 60)}...**\n\nLet me help you with that!\n\n\`\`\`typescript\n// Example code for your request\nconst solution = "This is where I'd provide actual AI-generated code";\nconsole.log(solution);\n\`\`\`\n\n### Key Points:\n- **Analysis**: I've processed your query carefully\n- **Solution**: The approach above demonstrates the pattern\n- **Next Steps**: Let me know if you need modifications\n\n> 💡 **Tip**: Connect a local GGUF model for full AI-powered responses!`,
      
      `Great question! Let me break this down for you:\n\n## 📝 Analysis\n\nBased on your request, here's my understanding:\n\n### What You Need:\n| Priority | Item | Status |\n|---------|------|--------|\n| High | Core logic | ✅ Ready |\n| Medium | Error handling | ✅ Included |\n| Low | Optimization | 🔄 Pending |\n\n\`\`\`javascript\n// Implementation example\nfunction solveProblem(input) {\n  // Step 1: Validate input\n  if (!input) throw new Error('Input required');\n  \n  // Step 2: Process data\n  const result = processData(input);\n  \n  // Step 3: Return output\n  return { success: true, data: result };\n}\n\`\`\`\n\nWould you like me to elaborate on any part?`,
      
      `I'd be happy to help! 🔧\n\n## Recommended Approach\n\nHere's a step-by-step solution:\n\n1️⃣ **Understand Requirements**\n   - Define clear acceptance criteria\n   - Identify edge cases\n\n2️⃣ **Design Solution**\n   - Choose appropriate patterns\n   - Consider performance implications\n\n3️⃣ **Implement**\n   - Write clean, testable code\n   - Add comprehensive comments\n\n\`\`\`python\n# Example implementation\ndef main():\n    \"\"\"Main entry point.\"\"\"\n    print("Hello from CodeMate!")\n    \n    # Your implementation here\n    return True\n\nif __name__ == "__main__":\n    main()\n\`\`\`\n\n💡 **Note**: This is a demo response. Load a local model for real AI assistance!\n\n---\n\n*Generated by CodeMate - Your Offline AI Assistant*`
    ];
    
    const response = responses[Math.floor(Math.random() * responses.length)];
    
    // Simulate streaming by adding words gradually
    let currentText = '';
    const words = response.split(' ');
    
    for (let i = 0; i < words.length; i++) {
      currentText += (i > 0 ? ' ' : '') + words[i];
      updateMessage(conversationId, messageId, currentText);
      await new Promise(resolve => setTimeout(resolve, 25 + Math.random() * 15));
    }
  };

  // Handle keyboard shortcuts
  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey && !isComposing) {
      e.preventDefault();
      handleSend();
    }
    
    // Ctrl+Enter for new line when in single-line mode (optional)
    if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') {
      // Allow default behavior - insert newline
    }
  };

  // Attach file
  const handleAttachFile = async () => {
    const path = await fileCommands.selectFile();
    if (path && !attachedFiles.includes(path)) {
      setAttachedFiles([...attachedFiles, path]);
    }
  };

  // Remove attached file
  const removeFile = (path: string) => {
    setAttachedFiles(attachedFiles.filter(f => f !== path));
  };

  return (
    <div className="border-t border-dark-800/80 bg-dark-900/50 backdrop-blur-sm">
      {/* Attached files */}
      {attachedFiles.length > 0 && (
        <div className="px-4 pt-3 flex flex-wrap gap-2">
          {attachedFiles.map((file) => (
            <span
              key={file}
              className="inline-flex items-center gap-2 px-3 py-1.5 bg-dark-800/80 rounded-lg text-xs border border-dark-700/50 group animate-in slide-in-from-bottom"
            >
              <svg className="w-3.5 h-3.5 text-primary-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              <span className="max-w-[120px] truncate text-dark-300">{file.split('/').pop()}</span>
              <button
                onClick={() => removeFile(file)}
                className="text-dark-500 hover:text-red-400 transition-colors opacity-0 group-hover:opacity-100"
              >
                <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </span>
          ))}
        </div>
      )}

      {/* Input area container */}
      <div className="p-4">
        <div className={`relative flex items-end gap-3 bg-dark-800/60 rounded-2xl border border-dark-700/60 focus-within:border-primary-500/50 focus-within:ring-2 focus-within:ring-primary-500/10 transition-all duration-200 ${isGenerating ? 'opacity-75' : ''}`}>
          {/* Textarea container with max height scrolling */}
          <div className="flex-1 relative overflow-hidden">
            <textarea
              ref={textareaRef}
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              onKeyDown={handleKeyDown}
              onCompositionStart={() => setIsComposing(true)}
              onCompositionEnd={() => setIsComposing(false)}
              placeholder={
                modelLoaded 
                  ? "Ask me anything about coding..." 
                  : "⚠️ Load a model first to start chatting..."
              }
              disabled={isGenerating || !modelLoaded}
              rows={1}
              className="w-full px-4 py-3 bg-transparent resize-none focus:outline-none text-white placeholder-dark-500 disabled:cursor-not-allowed disabled:opacity-60 pr-16 max-h-[160px] overflow-y-auto custom-scrollbar leading-relaxed"
              style={{ minHeight: '48px' }}
            />
            
            {/* Character count (when near limit) */}
            {message.length > 500 && (
              <span className="absolute bottom-2 right-14 text-[10px] text-yellow-500 font-mono">
                {message.length.toLocaleString()}
              </span>
            )}
          </div>

          {/* Action buttons */}
          <div className="flex items-center gap-1 pb-2 pr-2 shrink-0">
            {/* Attach file button */}
            <button
              onClick={handleAttachFile}
              disabled={isGenerating}
              className="p-2.5 rounded-xl hover:bg-dark-700/80 text-dark-400 hover:text-dark-200 disabled:opacity-40 transition-all duration-150"
              title="Attach file"
            >
              <svg className="w-[18px] h-[18px]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.8} d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13" />
              </svg>
            </button>

            {/* Send button */}
            <button
              onClick={handleSend}
              disabled={!message.trim() || isGenerating || !modelLoaded || isComposing}
              className={`
                p-2.5 rounded-xl transition-all duration-200 transform active:scale-95
                ${message.trim() && !isGenerating && modelLoaded
                  ? 'bg-gradient-to-r from-primary-600 to-primary-500 text-white shadow-md shadow-primary-600/30 hover:shadow-lg hover:from-primary-500 hover:to-primary-400'
                  : 'bg-dark-700/80 text-dark-500 cursor-not-allowed'
                }
              `}
              title="Send message (Enter)"
            >
              {isGenerating ? (
                /* Loading spinner */
                <svg className="w-[18px] h-[18px] animate-spin" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
              ) : (
                /* Send icon */
                <svg className="w-[18px] h-[18px]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
                </svg>
              )}
            </button>
          </div>
        </div>

        {/* Bottom status bar */}
        <div className="flex items-center justify-between mt-2.5 px-1">
          {/* Left side hints */}
          <div className="flex items-center gap-3 text-xs text-dark-600">
            {modelLoaded ? (
              <span className="flex items-center gap-1.5 text-emerald-500/70">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500"></span>
                Model ready
              </span>
            ) : (
              <span className="flex items-center gap-1.5 text-amber-500/70">
                <span className="w-1.5 h-1.5 rounded-full bg-amber-500"></span>
                No model loaded
              </span>
            )}
            
            <span className="hidden sm:inline">Enter to send • Shift+Enter for new line</span>
          </div>

          {/* Right side settings preview */}
          <div className="hidden md:flex items-center gap-3 text-xs text-dark-600">
            <span className="font-mono">T:{inferenceSettings.temperature}</span>
            <span className="text-dark-700">|</span>
            <span className="font-mono">{inferenceSettings.maxTokens.toLocaleString()}t</span>
          </div>
        </div>
      </div>
    </div>
  );
}
